#!/bin/sh

$CONFIG_SS='/root/shadowsocks/userapiconfig.py'
NODE_ID=${NODE_ID}
MU_SUFFIX=${MU_SUFFIX}
WEBAPI_URL=${WEBAPI_URL}
WEBAPI_TOKEN=${WEBAPI_TOKEN}
IP_MD5_SALT=${IP_MD5_SALT}

sed -i '/NODE_ID/c\NODE_ID = '"$NODE_ID" $CONFIG_SS
sed -i '/MU_SUFFIX/c\MU_SUFFIX = '"$NODE_ID" $CONFIG_SS
sed -i '/WEBAPI_URL/c\WEBAPI_URL = '"$NODE_ID" $CONFIG_SS
sed -i '/WEBAPI_TOKEN/c\WEBAPI_TOKEN = '"$NODE_ID" $CONFIG_SS
sed -i '/IP_MD5_SALT/c\IP_MD5_SALT = '"$NODE_ID" $CONFIG_SS

python3 /root/shadowsocks/server.py
